class MongoIndexConstant:
    tx_id = "tx_id"
    transfer_tx_id = "transfer_tx_id"
    transfer_block_number = "transfer_block_number"
    wallet_address = "wallet_address"
    tx_to_address = "tx_to_address"
    tx_from_address = "tx_from_address"
    tx_block_timestamp = "block_timestamp_1"
    blocks_number_hashed = "block_number_hashed"
    blocks_number_n_1 = "block_number_-1"
    blocks_number_1_type_hashed = "blocks_number_1_type_hashed"
    token_address_hashed = "token_address_hashed"
    transaction_block_number_input = "block_number_-1_input_hashed"
    token_transfer= "block_number_log_index"
